### ISSUE TITLE
Cmake version

### ISSUE THREAD

**Issue by bijlevel** [steinbergmedia/vst3projectgenerator#2]
I'm trying to 'clone and build' the app in MacOS Terminal, but I'm getting an error saying I'm running cmake 3.10.2 and cmake minimum 3.12 is required. I did download the latest cmake app and it is version 3.22.x. So what could be the problem?

**Comment by rehans** [comment]
Run ```cmake --version``` inside your terminal and tell me which version it puts out, please!

**Comment by bijlevel** [comment]
I did that already, but each time I use cmake in Terminal it sees it as a command and tells me unknown command. BTW the problem is solved by downloading the VST3 SDK that contained the already compiled app. Thanks for the reply!
